<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getConfigValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCg0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCglTdHJpbmcJY29uZmlnS2V5ID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxp
bmVDdXJzb3IsICJjb25maWdLZXkiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQpTdHJp
bmcgdmFsdWU9bnVsbDsNCnRyeSB7DQoJIHZhbHVlID1HbG9iYWxWYXJpYWJsZXNNYW5hZ2VyLmdl
dEluc3RhbmNlKCkuZ2V0R2xvYmFsVmFyaWFibGVWYWx1ZShjb25maWdLZXkpLmdldFZhbHVlKCk7
DQp9IGNhdGNoIChHbG9iYWxWYXJpYWJsZXNFeGNlcHRpb24gfCBQYXNzd29yZE1hbmFnZXJFeGNl
cHRpb24gZSkgew0KCS8vIFRPRE8gQXV0by1nZW5lcmF0ZWQgY2F0Y2ggYmxvY2sNCgllLnByaW50
U3RhY2tUcmFjZSgpOw0KfSANCi8vIHBpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNv
cl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNv
cl8xLCAiY29uZmlnVmFsdWUiLCB2YWx1ZSApOw0KcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7
DQoJ</value>
</Values>
